### ISSUE TITLE
Issues getting dnsmasq to run using sample command

### ISSUE THREAD

**Issue by andrakis** [gdm85/go-websockproxy#1]
Hello,

I'm trying to setup a local websockproxy using your library, but am facing troubles getting it to work.

I can successfully launch the application using:

```
$ sudo bin/go-websockproxy --listen-address=:8080 --tap-ipv4=10.5.0.1/16 --static-directory=jor1k --max-download-bandwidth=50kbps --max-upload-bandwidth=50kbps --log-
level=info
```

This was taken from the README.

However, I cannot get the `dnsmasq` example given to work:

```
$ sudo dnsmasq -d --bind-interfaces --listen-address=10.3.0.1 --dhcp-range=10.3.0.50,10.3.0.200,12h --dhcp-option=option:router,10.3.0.1 --dhcp-option=option:dns-server,10.3.0.1 --log-dhcp

dnsmasq: failed to create listening socket for 10.3.0.1: Cannot assign requested address
```

I thought perhaps the issue was that the IP address (`10.3.0.1`) is a little too dissimilar from the websockproxy's (`10.5.0.1`), but changing this did not result in a different error message or outcome.

I wonder if you could shed some light on the correct way to setup and use this proxy. Perhaps there are other steps I am not aware of.

Kind regards,
andrakis

**Comment by andrakis** [comment]
It seems there's more to setting this up than I thought. I hadn't created a TAP device before, which likely explains why dnsmasq wasn't managing to assign the address.

Apologies for opening up this issue before fully understanding the requirements.

**Comment by gdm85** [comment]
No worries, glad you solved it :+1:
